### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by ronsmits** [jamiebegin/metrics2mqtt#9]
After running pip3 install metrics2mqtt and starting it up I get the following error message:
```
pi@smartmeter:~ $ metrics2mqtt 
Traceback (most recent call last):
  File "/home/pi/.local/bin/metrics2mqtt", line 7, in <module>
    from metrics2mqtt.base import main
  File "/home/pi/.local/lib/python3.5/site-packages/metrics2mqtt/base.py", line 9, in <module>
    import json, jsons
  File "/home/pi/.local/lib/python3.5/site-packages/jsons/__init__.py", line 97, in <module>
    from jsons import (
  File "/home/pi/.local/lib/python3.5/site-packages/jsons/deserializers/__init__.py", line 13, in <module>
    from jsons.deserializers.default_dict import default_dict_deserializer
  File "/home/pi/.local/lib/python3.5/site-packages/jsons/deserializers/default_dict.py", line 2, in <module>
    from typish import get_args
  File "/home/pi/.local/lib/python3.5/site-packages/typish/__init__.py", line 24, in <module>
    from typish.functions._get_alias import get_alias
  File "/home/pi/.local/lib/python3.5/site-packages/typish/functions/_get_alias.py", line 36, in <module>
    'deque': typing.Deque,
AttributeError: module 'typing' has no attribute 'Deque'
```

Please advise

**Comment by ronsmits** [comment]
It was my bad :) the raspberrypi was running stretch with python 3.5 instead of 3.7 upgraded to buster and everything works
